.PHONY: clean All

All:
	@echo "----------Building project:[ cc - Debug ]----------"
	@cd "cc" && "$(MAKE)" -f  "cc.mk"
clean:
	@echo "----------Cleaning project:[ cc - Debug ]----------"
	@cd "cc" && "$(MAKE)" -f  "cc.mk" clean
